apiVersion: v1
kind: Secret
metadata:
  name: execution-secrets
  namespace: mechanics-execution
  labels:
    app: mechanics-execution
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=${DB_HOST};Port=5432;Database=execution;Username=${DB_USER};Password=${DB_PASSWORD}"
  ConnectionStrings__Mongo: "${MONGO_CONNECTION_STRING}"
  RABBITMQ_CONNECTION_STRING: "${RABBITMQ_CONNECTION_STRING}"
